### PR TITLE
fix: support connection lookup by ID

### PR DESCRIPTION
**Pull request by adityathebe**
Related: https://github.com/flanksource/flanksource-ui/issues/1378

### CODE REVIEW

**Comment by moshloop** [comment]
Isn't this already done via https://github.com/flanksource/duty/blob/main/connection.go#L67 ? or maybe we just need to handle the `connection://` prefix ?

**Comment by adityathebe** [comment]
@moshloop ya duty already handles it. However, incident commander was returning nil if the connection name didn't have `connection://` prefix.

**Comment by moshloop** [comment]
@adityathebe I think then lets add the support for the prefix in duty

**Comment by adityathebe** [comment]
@moshloop This PR is still needed though. Otherwise, HydrateConnection will never hit duty when a UUID is provided.

**Comment by adityathebe** [comment]
Related: https://github.com/flanksource/duty/pull/275

**Pull request merged**
